export const NEW_ENTRY_REQUEST = 'NEW_ENTRY_REQUEST'
export const NEW_ENTRY_SUCCESS = 'NEW_ENTRY_SUCCESS'
export const NEW_ENTRY_FAIL = 'NEW_ENTRY_FAIL'

export const GET_RECENT_ENTRIES_REQUEST = 'GET_RECENT_ENTRIES_REQUEST'
export const GET_RECENT_ENTRIES_SUCCESS = 'GET_RECENT_ENTRIES_SUCCESS'
export const GET_RECENT_ENTRIES_FAIL = 'GET_RECENT_ENTRIES_FAIL'

export const GET_ENTRIES_REQUEST = 'GET_ENTRIES_REQUEST'
export const GET_ENTRIES_SUCCESS = 'GET_ENTRIES_SUCCESS'
export const GET_ENTRIES_FAIL = 'GET_ENTRIES_FAIL'